CREATE DATABASE DonaMaria;


/*****************ESCOLA*****************/
CREATE TABLE ESCOLA(
    IDESCOLA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(12) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE ENDERECOESCOLA(
    IDENDESCOLA INT PRIMARY KEY AUTO_INCREMENT,
    ESTADO CHAR(2) NOT NULL,
    NUMERO VARCHAR(5) NOT NULL,
    CEP CHAR(8) NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    LOGRADOURO VARCHAR(255) NOT NULL,
    ID_ESCOLA INT NOT NULL
);


ALTER TABLE ENDERECOESCOLA
ADD CONSTRAINT FK_ESCOLA_ENDERECOESCOLA
FOREIGN KEY (ID_ESCOLA) REFERENCES ESCOLA(IDESCOLA);

/*******************RESPONSAVEL*************************/
CREATE TABLE RESPONSAVEL(
    IDRESPONSAVEL INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CPF CHAR(11) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(12) NOT NULL
);


/*******************ALUNO*************************/
CREATE TABLE ALUNO(
    IDALUNO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    MATRICULA VARCHAR(255) NOT NULL,
    TURMA VARCHAR(255) NOT NULL,
    TURNO ENUM('MATUTINO','VESPERTINO','INTEGRAL') NOT NULL,
    TELEFONE VARCHAR(12),
    EMAIL VARCHAR(255),
    SALDO DOUBLE(5,2) NOT NULL,
    ID_RESPONSAVEL INT NOT NULL
);

ALTER TABLE ALUNO
ADD CONSTRAINT FK_RESPONSAVEL_ALUNO
FOREIGN KEY (ID_RESPONSAVEL) REFERENCES RESPONSAVEL(IDRESPONSAVEL);

/*******************PRODUTO*************************/
CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO VARCHAR(255) UNIQUE NOT NULL,
    TIPO ENUM('Comida','Bebida') NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CAMINHOIMAGEM VARCHAR(255),
    FORNECEDOR VARCHAR(255),
    PRECO DOUBLE(10,2) NOT NULL
);

CREATE TABLE INGREDIENTE(
    INGREDIENTE VARCHAR(255) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    PRIMARY KEY (INGREDIENTE,ID_PRODUTO)
);

ALTER TABLE INGREDIENTE
ADD CONSTRAINT FK_PRODUTO_INGREDIENTE
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO);
/*******************COMPRA*************************/
CREATE TABLE COMPRA(
    IDCOMPRA INT PRIMARY KEY AUTO_INCREMENT,
    ID_ALUNO INT NOT NULL,  
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    DATAHORA DATETIME NOT NULL
);


ALTER TABLE COMPRA
ADD CONSTRAINT FK_ALUNO_COMPRA
FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(IDALUNO);

ALTER TABLE COMPRA
ADD CONSTRAINT FK_PRODUTO_COMPRA
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO);

/*******************USUARIO*************************/
CREATE TABLE USUARIO(
    IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_ESCOLA INT,
    ID_RESPONSAVEL INT,
    ID_ALUNO INT,
    NIVELACESSO ENUM('A','B','C') NOT NULL,
    USERLOGIN VARCHAR(30) NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_ALUNO_USUARIO
FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(IDALUNO);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_ESCOLA_USUARIO
FOREIGN KEY (ID_ESCOLA) REFERENCES ESCOLA(IDESCOLA);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_RESPONSAVEL_USUARIO
FOREIGN KEY (ID_RESPONSAVEL) REFERENCES RESPONSAVEL(IDRESPONSAVEL);
/*******************INSERÇÕES*************************/

INSERT INTO ESCOLA VALUES(NULL, 'Escola Mundial', '11993064521','escola.mundial@mail.com');

INSERT INTO ENDERECOESCOLA VALUES(NULL, 'SP', '231','04849529', 'Cantinho do céu', 'Rua 13 de Maio',1);

INSERT INTO RESPONSAVEL VALUES(NULL, 'José Rivera', '81524159875','jose_rivera@mail.com','11992568197');

INSERT INTO ALUNO VALUES(NULL, 'Cirilo Rivera', '144155986', '3º ano A', 'INTEGRAL', NULL, NULL, 0.00, 1);

INSERT INTO PRODUTO VALUES(NULL, '157', 'Comida', 'Enroladinho de Salsicha', NULL, NULL, 5.00);
INSERT INTO INGREDIENTE VALUES('Pão Branco', 1);
INSERT INTO INGREDIENTE VALUES('Salsicha', 1);

INSERT INTO PRODUTO VALUES(NULL, '158', 'Comida', 'Coxinha de Frango', NULL, NULL, 5.00);
INSERT INTO INGREDIENTE VALUES('Massa de Batata', 3);
INSERT INTO INGREDIENTE VALUES('Frango desfiado', 3);

INSERT INTO PRODUTO VALUES(NULL, '115', 'Bebida', 'Coca-Cola Lata 300ml', NULL, 'São Roque Distribuidora', 3.00);
INSERT INTO PRODUTO VALUES(NULL, '116', 'Bebida', 'Pepsi Lata 300ml', NULL, 'São Roque Distribuidora', 3.00);

INSERT INTO COMPRA VALUES(1, 1, 1, NOW());
INSERT INTO COMPRA VALUES(1, 3, 1, NOW());


INSERT INTO USUARIO VALUES(NULL, 1, NULL, NULL, 'A', 'admin','$2y$10$NH4KNRpwzpBI0ejWbzpz0uychCgFE8ZxradcLfZFnNdLvWpLmPAWy');
INSERT INTO USUARIO VALUES(NULL, NULL, 1, NULL, 'B', 'resp','$2y$10$NH4KNRpwzpBI0ejWbzpz0uychCgFE8ZxradcLfZFnNdLvWpLmPAWy');
INSERT INTO USUARIO VALUES(NULL, NULL, NULL, 1, 'C', 'aluno','$2y$10$NH4KNRpwzpBI0ejWbzpz0uychCgFE8ZxradcLfZFnNdLvWpLmPAWy');


SELECT NOME,USERLOGIN
FROM ALUNO
INNER JOIN USUARIO
ON ALUNO.IDALUNO = USUARIO.ID_ALUNO;


SELECT CODIGO,TIPO,NOME,INGREDIENTE,FORNECEDOR,CAMINHOIMAGEM,PRECO
FROM PRODUTO
INNER JOIN INGREDIENTE
ON INGREDIENTE.ID_PRODUTO = PRODUTO.IDPRODUTO;

SELECT IDRESPONSAVEL,NOME,CPF,EMAIL,TELEFONE,USERLOGIN,NIVELACESSO FROM responsavel
INNER JOIN usuario
ON responsavel.IDRESPONSAVEL = usuario.ID_RESPONSAVEL;